MODULE ManufacturingOrderNotification;

REQUIRE ProjectManufacturingOrder, MaxMessenger, ProjectAssignment;

NAMESPACE Manufacturing;

CLASS ManufacturingOrderAssignee 'Assignee';

manufacturingOrder = DATA ManufacturingOrder (ManufacturingOrderAssignee) NONULL DELETE INDEXED;
employee = DATA Employee (ManufacturingOrderAssignee) NONULL INDEXED;
nameEmployee 'Employee' (ManufacturingOrderAssignee a) = name(employee(a));

sendToMax 'Max' = DATA BOOLEAN (ManufacturingOrderAssignee);
sendToEmail 'Email' = DATA BOOLEAN (ManufacturingOrderAssignee);

countAssignees (ManufacturingOrder o) = GROUP SUM 1 IF manufacturingOrder(ManufacturingOrderAssignee a) = o;

WHEN (SETCHANGED(project(ManufacturingOrder o)) OR SETCHANGED(scheduledDateTime(o)))
    AND project(o) AND scheduledDateTime(o) AND NOT countAssignees(o) DO {
    FOR assigned(project(o), Employee e, DATE(scheduledDateTime(o))) DO NEW a = ManufacturingOrderAssignee {
        manufacturingOrder(a) <- o;
        employee(a) <- e;
    }
}

//notifications
sendNotificationManufacturingOrder 'Отправка уведомлений по производственому заказу' ABSTRACT LIST (ManufacturingOrder, STRING);

textMessageComment(ManufacturingOrderComment c) = CONCAT '\n',
    '💬 Новый комментарий',
    '📋 Заказ №' + number(manufacturingOrder(c)),
    '👤 ' + fullName(user(c)),
    '',
    [FORMULA STRING 'btrim(regexp_replace(regexp_replace($1, \'</p>|<br[^>]*>\', chr(10), \'gi\'), \'<[^>]+>\', \'\', \'g\'))'](text(c));

addedFile 'Added' = DATA LOCAL BOOLEAN (ManufacturingOrderFile);
WHEN SETCHANGED(file(ManufacturingOrderFile f)) DO addedFile(f) <- TRUE;

countAddedFiles (ManufacturingOrder o) = GROUP SUM 1 IF addedFile(ManufacturingOrderFile f) AND manufacturingOrder(f) = o;
namesAddedFiles (ManufacturingOrder o) = GROUP CONCAT (CONCAT '.', name(ManufacturingOrderFile f), extension(f)), '\n'
    IF addedFile(f) AND manufacturingOrder(f) = o ORDER f;
lastAddedFile (ManufacturingOrder o) = GROUP LAST ManufacturingOrderFile f ORDER f WHERE addedFile(f) AND manufacturingOrder(f) = o;
userAddedFiles (ManufacturingOrder o) = fullName(user(lastAddedFile(o)));

textMessageFiles(ManufacturingOrder o) = CONCAT '\n',
    '📎 Добавлено файлов: ' + countAddedFiles(o),
    '📋 Заказ №' + number(o),
    '👤 ' + userAddedFiles(o),
    '',
    namesAddedFiles(o);

WHEN SETCHANGED (text(ManufacturingOrderComment c)) AND ManufacturingOrder o = manufacturingOrder(c) DO sendNotificationManufacturingOrder(o, textMessageComment(c));

WHEN countAddedFiles(ManufacturingOrder o) DO {
    sendNotificationManufacturingOrder(o, textMessageFiles(o));
    addedFile(ManufacturingOrderFile f) <- NULL WHERE addedFile(f) AND manufacturingOrder(f) = o;
}

sendNotificationManufacturingOrderEmail(ManufacturingOrder o, Employee e, STRING s){
    EMAIL
        SUBJECT s
        TO MasterData.email(e)
        BODY s;
    ;
}

sendNotificationManufacturingOrder(ManufacturingOrder o, STRING s)+{
    FOR manufacturingOrder(ManufacturingOrderAssignee a) = o AND sendToEmail(a) DO {
        sendNotificationManufacturingOrderEmail(o, employee(a), s);
    }
}

chat 'Чат Max' = DATA Chat(Employee);
nameChat 'Чат Max' (Employee e)= name(chat(e));

EXTEND FORM employee
    PROPERTIES(e) nameChat AFTER email(e)
;

DESIGN employee {
    info {
        MOVE PROPERTY (nameChat(e));
    }
}

sendNotificationManufacturingOrderMessenger(ManufacturingOrder o, Employee e, STRING s){
    sendMessage(chat(e), s);
}

sendNotificationManufacturingOrder(ManufacturingOrder o, STRING s)+{
    FOR manufacturingOrder(ManufacturingOrderAssignee a) = o AND sendToMax(a) AND chat(employee(a)) DO {
        sendNotificationManufacturingOrderMessenger(o, employee(a), s);
    }
}

EXTEND FORM manufacturingOrder
    OBJECTS a = ManufacturingOrderAssignee
    PROPERTIES(a) nameEmployee, sendToMax, sendToEmail, NEW, DELETE
    FILTERS manufacturingOrder(a) = o
;

DESIGN manufacturingOrder {
    details {
        NEW notifications {
            caption = badged('Assignees', countAssignees(o));
            MOVE BOX(a) { caption = ''; }
        }
    }
}
