MODULE ManufacturingOrderExtra;

REQUIRE ManufacturingOrder;

planeDateTime 'Плановое Завершение' = DATA DATE (ManufacturingOrder) IN id;

EXTEND FORM manufacturingOrder
    PROPERTIES(o) READONLYIF readonly(o)
    planeDateTime
;

DESIGN manufacturingOrder {
    headerLeft {
        MOVE PROPERTY(planeDateTime(o)) AFTER PROPERTY (scheduledDateTime(o));
    }
}

EXTEND FORM manufacturingOrders
    PROPERTIES (o) READONLY planeDateTime AFTER scheduledDateTime(o)
;

statusMfgFile 'Статус/Примечание' = DATA ISTRING[50] (ManufacturingOrderFile);

EXTEND FORM manufacturingOrder
    PROPERTIES (of) statusMfgFile AFTER description(of)
;


